name: null
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope
  - argh
  - astroid
  - asttokens
  - attrs
  - backcall
  - backports
  - backports.functools_lru_cache
  - bzip2
  - ca-certificates
  - colorama
  - decorator
  - dill
  - docopt
  - executing
  - iniconfig
  - ipython
  - isort
  - jedi
  - lazy-object-proxy
  - libffi
  - libzlib
  - matplotlib-inline
  - mccabe
  - ncurses
  - openssl
  - packaging
  - parso
  - pexpect
  - pickleshare
  - pip
  - platformdirs
  - pluggy
  - prompt-toolkit
  - ptyprocess
  - pure_eval
  - py
  - pygments
  - pylint
  - pyparsing
  - pytest
  - pytest-watch
  - python
  - python_abi
  - pyyaml
  - readline
  - setuptools
  - six
  - sqlite
  - stack_data
  - tk
  - tomli
  - traitlets
  - typing_extensions
  - tzdata
  - watchdog
  - wcwidth
  - wheel
  - wrapt
  - xz
  - yaml
  - zlib
